spring.application.name=BankApi

spring.security.user.name=user
spring.security.user.password=123

#spring.datasource.url=jdbc:postgresql://localhost:5432/bankApi
#spring.datasource.username=postgres
#spring.datasource.password=102836547

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#jwt.secret=MojSuperTajnyKluczDoJWTKtoryMaPonad32Znaki2024!!
jwt.secret=${JWT_SECRET}